server.port=8080
spring.application.name=futmarket

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/futmarket?options=-c%20TimeZone=America/Argentina/Buenos_Aires
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# Valuation strategy configuration
futmarket.valuation.base-value=1.0
futmarket.valuation.scale-factor=10.0

# JWT configuration
futmarket.jwt.secret=${JWT_TOKEN}
futmarket.jwt.expiration=86400000
