name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Compilar con Maven
        run: mvn -B clean compile

  coverage:
    name: Run Coverage and SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build
    env:
      JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
      FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
    steps:
      - name: Checkout completo del historial
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Desactiva los shallow clones para que Sonar asocie bien los commits

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven' # Activa el caché nativo de dependencias de Maven para acelerar el build

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Ejecutar Tests, JaCoCo y análisis de SonarCloud
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=thiagosofarelli_futmarket \
            -Dsonar.organization=futmarket \
            -Dsonar.coverage.jacoco.xmlReportPaths=${{ github.workspace }}/target/site/jacoco/jacoco.xml
